### ISSUE TITLE
Rework dcclist

### ISSUE THREAD

**Issue by thommey** [eggheads/eggdrop#155]
The current dcclist output is completely unparsable and lacks information (please someone add details about what's missing).
We need to rework it or introduce a new command and deprecate dcclist in the manually.
Missing: at least SSL info
Found by: jack3

**Comment by ghost** [comment]
Was this fixed by #555 ?

**Comment by Cizzle** [comment]
If you can't come up with things that are missing, then this is fixed.

**Comment by ghost** [comment]
He was saying that
(1) it's not parsable (how isn't it?)
(2) other information was missing (no specific items suggested)
(3) I patched the SSL issue already.

Looks like it was a third-party comment anyway to begin with. I'm not sure what can't be parsed out (the type is rather dynamic, yes but ...) but it's a proper list, and the data positions don't change.

Now, I'm just curious.

**Comment by Cizzle** [comment]
Looking at it closer I might say that these things are missing;
 - SERVER-types don't have the port (and TLS) info
 - if an IP doesn't resolve to a hostname, it's an empty element; I feel the IP could be used then
Anyone concur?

**Comment by ghost** [comment]
> SERVER-types don't have the port (and TLS) info

I agree. That would be useful; see 'which' of the server entries connected if there are more than one entry for a given serv-but-different ports (some people use SSL, with a non-SSL fall-back in the list)

> if an IP doesn't resolve to a hostname, it's an empty element; I feel the IP could be used then

Good point.

I like both.
